# Generated by Django 5.0.7 on 2025-10-22 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ticketattachment_ticketcomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CREATED', 'Création'), ('STATUS_CHANGED', 'Changement de statut'), ('PRIORITY_CHANGED', 'Changement de priorité'), ('ASSIGNED', 'Attribution'), ('COMMENT_ADDED', 'Commentaire ajouté'), ('ATTACHMENT_ADDED', 'Pièce jointe ajoutée')], max_length=32)),
                ('message', models.TextField()),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
