# Generated by Django 5.0.7 on 2025-10-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticketevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ('order', '-created_at')},
        ),
        migrations.AddField(
            model_name='ticket',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
