# Generated by Django 5.0.7 on 2025-10-22 16:25

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_invoice_unique_together_invoice_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activity_kind',
            field=models.CharField(choices=[('VENTES', 'Vente de marchandises / hébergement (BIC)'), ('SERVICES_BIC', 'Prestations de services (BIC)'), ('LIB_BNC', 'Libéral non réglementé (BNC)'), ('LIB_CIPAV', 'Libéral réglementé (CIPAV)')], default='SERVICES_BIC', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_status',
            field=models.CharField(choices=[('MICRO', 'Micro-entreprise'), ('EI_REEL', 'Entreprise individuelle - régime réel'), ('EURL_IS', "EURL/SARL à l'IS (gérant TNS)"), ('SASU_IS', "SASU/SAS à l'IS (assimilé salarié)")], default='MICRO', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='tva_franchise',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='company',
            name='urssaf_frequency',
            field=models.CharField(choices=[('MENSUEL', 'Mensuel'), ('TRIMESTRIEL', 'Trimestriel')], default='TRIMESTRIEL', max_length=12),
        ),
        migrations.CreateModel(
            name='LegalThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('micro_cap_sales', models.PositiveIntegerField(default=188700)),
                ('micro_cap_services', models.PositiveIntegerField(default=77700)),
                ('vat_base_sales', models.PositiveIntegerField(default=85000)),
                ('vat_base_sales_tol', models.PositiveIntegerField(default=93500)),
                ('vat_base_services', models.PositiveIntegerField(default=37500)),
                ('vat_base_services_tol', models.PositiveIntegerField(default=41250)),
            ],
            options={
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='TurnoverEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('source', models.CharField(choices=[('MANUEL', 'Saisie manuelle'), ('INVOICE', 'Factures'), ('IMPORT', 'Import CSV')], default='MANUEL', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnover_entries', to='core.company')),
            ],
            options={
                'ordering': ['-period_start'],
                'unique_together': {('company', 'period_start', 'period_end', 'source')},
            },
        ),
    ]
